config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "recipes#index"
  get "/about", to: "pages#about"
  get "/privacy-policy", to: "pages#privacy_policy"
  get "/recipes/mine", to: "recipes#mine"
  get "/recipes/meal", to: "recipes#meal"
  resources :recipes

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe
  default_scope { order(order: :asc) }
  validates :step, :order, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  validates :name, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
  	has_many :ingredients, dependent: :destroy
  	has_many :directions, dependent: :destroy
    mount_uploader :picture, PictureUploader
    validate  :picture_size

  	accepts_nested_attributes_for :ingredients,
    															reject_if: proc { |attributes| attributes['name'].blank? },
    															allow_destroy: true
   	accepts_nested_attributes_for :directions,
    															reject_if: proc { |attributes| attributes['step'].blank? },
    															allow_destroy: true

    validates :title, :description, :picture, :meal_category, presence: true
    validates :description, length: { maximum: 280 }

    private
      # Validates the size of an uploaded picture.
      def picture_size
        if picture.size > 5.megabytes
          errors.add(:picture, "should be less than 5MB")
        end
      end
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, :dependent => :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @description = "Recipes Without Blogs - About the project."
    end

    def privacy_policy 
        @description = "Recipes Without Blogs - Privacy policy"
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :meal]
  before_action :correct_user, only: [:edit, :update, :destroy]
  def index
    params[:page] ? page = params[:page] : page = 1
    @recipes = Recipe.order("created_at DESC").offset((page.to_i * 10) - 10).first(10)
    @page_count = (Recipe.count.to_i / 10) + 1
  end

  def show
    @current_user = current_user
    @description = @recipe.description
    @image_url = @recipe.picture.url
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to @recipe, notice: "Successfully created new recipe"
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path, notice: "Successfully deleted recipe"
  end

  def mine
    @recipes = Recipe.where(user_id: current_user.id).order("created_at DESC")
  end

  def meal 
    params[:page] ? page = params[:page] : page = 1
    @recipes = Recipe.order("created_at DESC").where(meal_category: params[:slug]).offset((page.to_i * 10) - 10).first(10)
    @meal = params[:slug]
    @page_count = (Recipe.where(meal_category: params[:slug]).count.to_i / 10) + 1
    render "index"
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:title, :description, :meal_category, :picture, :slug, :page, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :order, :_destroy])
  end

  def correct_user
    @user = User.find(Recipe.find(params[:id]).user_id)
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-133603965-3"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-133603965-3');
    </script>
    <title>Recipes Without Blogs</title>
    <!-- OG Tags -->
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Recipes Without Blogs" />
    <meta property="og:description" content="<%= @description ? @description : "Just recipes. No backstories."%>" />
    <meta property="og:image" content="<%= @image_url ? @image_url : "https://s3-us-west-2.amazonaws.com/recipes-without-blogs/rwb-logo.png" %>" />
    <meta property="og:locale" content="en_US" />

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/partials/nav" %>
    <main class="page-content">
      <% flash.each do |name, msg| %>
        <aside>
          <%= msg %>
        </aside>
      <% end %>
      <%= yield %>
    </main>
    <%= render "layouts/partials/footer" %>
  </body>
</html>

app/views/layouts/partials/_footer.html.erb
<footer>
    <p>Report problems or make suggestions <a href="https://github.com/ogdenstudios/recipeswithoutblogs/issues">on GitHub</a> or <a href="mailto:tyler@ogdenstudios.xyz">via email</a>.</p>
    <p><%= link_to "Read our privacy policy", privacy_policy_path %></p>
</footer>

app/views/layouts/partials/_nav.html.erb
<nav class='navbar'>
  <%= link_to 'Home', root_path, class: 'nav-link' %>
  <%= link_to 'About', about_path, class: 'nav-link' %>
  <% if user_signed_in? %>
    <%= link_to 'New Recipe', new_recipe_path, class: 'nav-link' %>
    <%= link_to 'Your Recipes', recipes_mine_path, class: 'nav-link' %>
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
  <% else %>
    <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
    <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
  <% end %>
</nav>

app/views/pages/about.html.erb
<h1>What is Recipes Without Blogs?</h1>
<p>Recipes Without Blogs is a website where people can submit and read recipes with a guarantee those recipes will never be accompanied by unnecessary blog posts or blog-post-like text.</p>
<p>Recipes on this website will only ever contain:<p>
<ol>
    <li>A short description (280 characters or fewer)</li>
    <li>A list of ingredients</li>
    <li>A list of instructions</li>
    <li>One featured image</li>
</ol>

<h1>Why does it look... bad?</h1>
<p>When I built this website, I set out to improve user experience as much as possible. It started with an idea to strip out the blog posts from internet recipes. Then, I was introduced to <a href="https://brutalist-web.design/">Brutalist Web Design</a>, and I realized the natural evolution of RWB would be a website that incorporates brutalist design.</p>
<p>The site might look bad or wrong at first, because many popular web sites are designed as applications, not web documents. By implementing Brutalist Web Design princples, I think this website will have excellent readability, usability, accessability, and performance. After you use the site for a while, I hope you'll come to love brutal design and its applications.</p>

<h1>I love it! How can I help?</h1>
<p>I'm glad you like the website! I worked very hard on it in my spare time. The best way you can help RWB thrive is by signing up as a user and adding your own recipes.</p>
<p>If you're a web developer, designer, server admin, or you're learning how to do those things, you can contribute via <a href="https://github.com/ogdenstudios/recipeswithoutblogs">GitHub</a>, or <a href="mailto:tyler@ogdenstudios.xyz">email me</a> about contributing code and/or your expertise.</p>
<p>Servers ain't free, and my time isn't either, so you can also <a href="https://ko-fi.com/ogdenstudios">buy me a coffee</a>, if that floats your boat.</p>

<h1>I hate it! This is a stupid idea</h1>
<p>Cool! Feel free to submit a PR on <a href="https://github.com/ogdenstudios/recipeswithoutblogs">GitHub</a> with how you'd do it better. Or don't. I'm a web developer, <a href="https://imgur.com/gallery/mSHi8">not a cop</a>.

app/views/pages/privacy_policy.html.erb
<h1>Privacy Policy</h1>

<p>This is a privacy policy for the Recipes Without Blogs website, <a href="https://recipeswithoutblogs.com">https://recipeswithoutblogs.com</a>.</p>

<h2>Types of personal information we collect</h2>

<p>We collect the following information from users:</p>
<ul>
    <li>Email address</li>
</ul>

<p>We use this information to create accounts and send password resets.</p>

<h2>Location information</h2>

<p>We do not collect location information</p>

<h2>Analytics tools</h2>

<p>We use Google Analytics and cookies to monitor website traffic to our site. By using this site, you agree to us using this information for our analytics purposes.</p>

<h2>Law enforcement personal information requests</h2>

<p>We will never disclose personal information of users to law enforcement agents, unless compelled by law.</p>

<h2>Removal of information</h2>

<p>You can formally request to have your information removed from the website by emailing <a href="mailto:tyler@ogdenstudios.xyz">tyler@ogdenstudios.xyz</a>

app/views/recipes/_card.html.erb
<article class="recipe__card">
  <h2><%= link_to recipe.title, recipe, id: "link-to-recipe-#{recipe.id}" %></h2>
  <%= image_tag recipe.picture.url %>
</article>

app/views/recipes/_direction_fields.html.erb
<div class="direction-container nested-fields" draggable="true" ondragstart="dragstart(event)" ondragover="dragover(event)" ondragenter="dragenter(event)" ondrop="drop(event)">
  <%= f.hidden_field :order, value: f.object.order, label: false, class: "hidden-order-field" %>
  <%= f.input :step, label: false, class: "direction-textarea" %>
  <%= link_to_remove_association "Delete", f %>
</div>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe, { multipart: true} do |f| %>

	<% if @recipe.errors.any? %>
		<div id="errors">
			<ul>
			<% @recipe.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div>
		<label for="recipe[title]">* Title</label>
		<%= f.input :title, label: false %>
		<label for="recipe[description]">* Description: 280 character limit </label><span id="charactersLeft">(0/280)</span>
		<%= f.input :description, label: false %>
		<label for="recipe[meal_category]">* Meal category</label><br />
		<select name="recipe[meal_category]" required="true">
			<option>breakfast</option>
			<option>lunch</option>
			<option>dinner</option>
			<option>dessert</option>
			<option>other</option>
		</select>
		<br />
		<label for="recipe[picture]">* Picture: as high resolution as possible, square if you can. Will be cropped to 400x400</label>
		<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
		<div>
			<h3>Ingredients</h3>
			<p>Add ingredients, including quantities</p>
			<div id="#ingredients">
				<%= f.simple_fields_for :ingredients do |ingredient| %>
					<%= render 'ingredient_fields', f: ingredient %>
				<% end %>
			<div>
				<%= link_to_add_association 'Add Ingredient', f, :ingredients %>
			</div>
		</div>
		<div>
			<h3>Directions</h3>
			<p>Add directions, step by step</p>
			<div id="#directions">
				<%= f.simple_fields_for :directions do |direction| %>
					<%= render 'direction_fields', f: direction %>
				<% end %>
			<div>
				<%= link_to_add_association 'Add Step', f, :directions %>
			</div>
		</div>
	</div>
<%= f.button :submit, id: "recipe-submit" %>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields">
	<%= f.input :name, label: false %>
	<%= link_to_remove_association "Delete", f %>
</div>

app/views/recipes/_pagination_nav.html.erb
<nav class="pagination">
  Page:
  <ul>
    <% (1..page_count).each do |i| %>
      <% if meal %>
        <li><%= link_to(i.to_s, recipes_meal_path(slug: meal, page: i.to_s)) %></li>
      <% else %>
        <li><%= link_to(i.to_s, recipes_path(page: i.to_s)) %></li>
      <% end %>
    <% end %>
  </ul>
</nav>

app/views/recipes/_recipe_nav.html.erb
<nav>
<%= link_to 'All', recipes_path %>
<%= link_to 'Breakfast', recipes_meal_path(slug: 'breakfast') %>
<%= link_to 'Lunch', recipes_meal_path(slug: 'lunch') %>
<%= link_to 'Dinner', recipes_meal_path(slug: 'dinner') %>
<%= link_to 'Other', recipes_meal_path(slug: 'other') %>
</nav>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render "recipe_nav" %>
<h1><%= @meal ? @meal.titlecase : "Recipes" %></h1>
<% if @page_count > 1 %>
<%= render 'pagination_nav', meal: @meal, page_count: @page_count%>
<% end %>
<% @recipes.each do |recipe| %>
  <%= render "card", recipe: recipe %>
<% end %>
<% if @page_count > 1 %>
<%= render 'pagination_nav', meal: @meal, page_count: @page_count%>
<% end %>

app/views/recipes/meal.html.erb
<%= link_to "All", recipes_path %>
<%= link_to "Breakfast", recipes_meal_path(slug: "breakfast") %>
<%= link_to "Lunch", recipes_meal_path(slug: "lunch") %>
<%= link_to "Dinner", recipes_meal_path(slug: "dinner") %>
<%= link_to "Other", recipes_meal_path(slug: "other") %>

<h1><%= @meal.titlecase %></h1>
<% @recipes.each do |recipe| %>
  <div class="recipe__card">
    <%= image_tag recipe.picture.url %>
    <h2><%= link_to recipe.title, recipe %></h2>
    <hr />
  </div>
<% end %>

app/views/recipes/mine.html.erb
<h1>Recipes you have submitted</h1>
<ul>
    <% @recipes.each do |recipe| %>
    <li><%= link_to recipe.title, recipe %></li>
    <% end %>
</ul>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render 'form' %>
<br />
<%= link_to "Back", root_path %>

app/views/recipes/show.html.erb
<div>
  <div id="recipe_top">
    <div>
      <%= image_tag @recipe.picture.url if @recipe.picture?%>
    </div>
  </div>
  <div>
    <div>
      <div id="recipe-info">
        <h1><%= @recipe.title %></h1>
        <p><%= @recipe.description %></p>
      </div>
    </div>
    <div>
      <div>
        <div id="ingredients">
          <h2>Ingredients</h2>
          <ul>
            <% @recipe.ingredients.each do |ingredient| %>
              <li><%= ingredient.name %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div>
      <div>
        <div id="directions">
          <h2>Directions</h2>
          <ol>
            <% @recipe.directions.order(:order).each do |direction| %>
              <li><%= direction.step %></li>
            <% end %>
          </ol>
        </div>
      </div>
    </div>
    <div>
      <div>
        <% if user_signed_in? && @current_user.id == @recipe.user_id %>
          <%= link_to "Edit", edit_recipe_path %>
          <%= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
        </div>
      </div>
    </div>